kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: ssc-aws-s3-bucket
  namespace: kasten-io
spec:
  locationSpec:
    type: ObjectStore
    objectStore:
      name: ssc-aws-s3-bucket
      objectStoreType: S3
      path: k10/c9273888-43f3-4d78-b025-e626aa51341a/migration
      pathType: Directory
      region: us-east-1
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: k10secret-wl9sm
        namespace: kasten-io
  type: Location
