kind: TransformSet
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: kasten-podnetwork-transformset
  namespace: kasten-io
spec:
  transforms:
    - subject:
        name: petclinic
        resource: routes
      name: route-transform
      json:
        - op: replace
          path: /spec/host
          value: petclinic-kasten-podnetwork.apps.cluster-ls528.dynamic.redhatworkshops.io
