kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: kasten-localnet-backup
  namespace: kasten-io
spec:
  frequency: "@daily"
  retention:
    daily: 2
  selector:
    matchExpressions:
      - key: k10.kasten.io/appNamespace
        operator: In
        values:
          - kasten-localnet
  actions:
    - action: backup
      backupParameters:
        filters: {}
        profile:
          name: ssc-aws-s3-bucket
          namespace: kasten-io
    - action: export
      exportParameters:
        frequency: "@daily"
        receiveString: bIzAPpoanmEFxTpqpj8wssVebHIaIXmG+gO03V4KW708EsxZnUCSUJCZap+M4tc9AzXkzKuNGU+u7zELhTr9rBgV7SocFLuyTIi+y+e85rWtiPZW6HZJMwno4ZCJJKsxZpBIo294w+tHu7OQ7NzFzkOwBPmU9kFjwmzOM2KM7ci27JYkMmWQtk+TuUP9Axxn9+hzNK6khVhI00o3MTiL9929XXSzHSjrpihH94zbaJdioYyeZS3AdosMu6SFyo31Nd+eZqiLdZxhGzb/p1tgpzaarbWeauPJ3hCxFWhlTlFqRnWF4ScBpzb38s/D4cEvngwreYoHgi9YwZlywmbTTLNIpfkVb0pbp5V02sbku/Gl1x/H3ImE5il6jw701mw4uZSvNNZYzO25FDIwwYKqOUbnlqheE+XUrEC/iMYCICpHm9ZWMdTOL2VTHUDKnv/0NB3Rp7Q8fv7gC0MAsF9jWHSujIBjqek9YzT/bWJOqcNe+T0CiB2HAylbInxSTZWh2+KDYAXCgi8+9oAAwAyzkiFIufoyWPG4ejRoYdXkzXEltY+2AYmhzcnkqHgUEzqm4FQ
        profile:
          name: ssc-aws-s3-bucket
          namespace: kasten-io
        migrationToken:
          name: kasten-localnet-backup-migration-token
          namespace: kasten-io
        exportData:
          enabled: true
      retention:
        daily: 4
  createdBy: kasten-io:k10-k10
  modifiedBy: kasten-io:auth-svc
  lastModifyHash: 1984411509
